#!/bin/bash

if [[ $USER != 'root' ]]; then
	echo "Maaf, Anda harus menjalankan ini sebagai root"
	exit
fi

MYIP=$(wget -qO- ipv4.icanhazip.com)

#vps="zvur";
vps="aneka";

if [[ $vps = "zvur" ]]; then
	source="http://scripts.gapaiasa.com"
else
	source="http://anekascript.anekavps.us"
fi

# go to root
cd

disable-user-expire
clear

echo "---------------------------- DAFTAR AKUN SSH EXPIRE ----------------------------"

if [[ $vps = "zvur" ]]; then
	echo "                     ALL SUPPORTED BY Black SSH                     "
	echo "             https://www.facebook.com/groups/1837219976498058/             "
else
	echo "                           ALL SUPPORTED BY Black SSH                          "
	echo "                     https://www.facebook.com/groups/1837219976498058/                      "
fi

	echo "            DEVELOPED BY Black SSH            "
echo ""

cat /root/expireduser.txt
echo ""

cd ~/
rm -f /root/IP
